### ISSUE TITLE
[GeoNature] : taches mise à jour mars 2022 (v2.10.0.dev0 - feat/sinp)

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#183]
Avant le passage en production de la MAJ de GN :

- [x] Mettre à jour les logos du CBNA et du CBNMed sur Silene Expert (GeoNature)
- [x] Réactiver la case "espèces sensibles" dans le formulaire de demande d'accès avec la phrase suivante : "Je souhaite accéder aux [données sensibles flore](https://silene.eu/ressources-documentaires/donnees-sensibles/). Avant de cocher cette case, veuillez-vous assurer que vous remplissez [les conditions d'octroi](https://silene.eu/wp-content/uploads/2022/03/ReglesAccesDSFlore-2022-VF.pdf). Veuillez également renseigner le champ description de manière détaillée dans la motivation de votre demande"
- [x] Mettre à jour le texte de la page d'accueil de Silene Expert #155 
- [x] Mettre à jour le texte de la convention d'accès aux données #105 
- [x] Paramétrer correctement les filtres de statuts de protection #182
- [x] Modifier le format d'export de la Synthese #70 
taxons pour mettre à jour la page "données". 
- [x] Mettre à jour les logos du CBNA et du CBNMed sur Silene Nature (Atlas)
- [x] Corriger l'affichage des logos sur le CMS silene.eu dans le pied de page
- [x] Résoudre les nouveaux tickets 
  - [x] #184
  - [x] #185
  - [x] #186
  - [x] #187
  - [x] #188
- [x] Transmettre à @gkapfer le nombre de données totales (faune + flore), et le nombre de

**Comment by jpm-cbna** [comment]
@okristo Pour la case "espèces sensibles", pourrais tu m'indiquer dans la phrase sur quels termes mettre le lien vers "[documents espèces sensibles flore](https://silene.eu/ressources-documentaires/donnees-sensibles/)".

Par ailleurs, pourrais tu m'indiquer le lien à placer sur les termes "le document à télécharger ici". Je n'ai pas l'impression que cela correspond au lien précédent...

**Comment by okristo** [comment]
@jpm-cbna J'ai mis à jour le premier post de ce ticket avec les liens à jour et au bon endroit.

**Comment by okristo** [comment]
Le 2ème point de la liste de taches n'est plus visible dans le demande d'accès : 
Réactiver la case "espèces sensibles" dans le formulaire de demande d'accès avec la phrase suivante : "Je souhaite accéder aux [données sensibles flore](https://silene.eu/ressources-documentaires/donnees-sensibles/). Avant de cocher cette case, veuillez-vous assurer que vous remplissez [les conditions d'octroi](https://silene.eu/wp-content/uploads/2022/03/ReglesAccesDSFlore-2022-VF.pdf). Veuillez également renseigner le champ description de manière détaillée dans la motivation de votre demande"

**Comment by jpm-cbna** [comment]
Il faut penser à maintenir à jour le fichier `geonature/frontend/src/assets/i18n/fr.json` qui contient une valeur modifiée pour le paramètre `sensitiveAccessText`.
